# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MajorLogin_res.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'MajorLogin_res.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MajorLogin_res.proto\x12\nmajorlogin\"\x8d\x03\n\rMajorLoginRes\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x14\n\x0c\x62lock_region\x18\x03 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63\x63ount_jwt\x18\x08 \x01(\t\x12\x16\n\x0eseconds_offset\x18\t \x01(\x05\x12\x14\n\x0c\x61\x63\x63ount_host\x18\n \x01(\t\x12\x16\n\x0e\x65mulator_score\x18\x0c \x01(\x05\x12\'\n\tnested_15\x18\x0f \x01(\x0b\x32\x14.majorlogin.Nested15\x12\x13\n\x0bserver_list\x18\x10 \x01(\t\x12\x0c\n\x04\x63ity\x18\x13 \x01(\t\x12\x13\n\x0bregion_code\x18\x14 \x01(\t\x12\x0f\n\x07some_id\x18\x15 \x01(\x03\x12\x0b\n\x03key\x18\x16 \x01(\x0c\x12\n\n\x02iv\x18\x17 \x01(\x0c\x12\x16\n\x0eserver_list_24\x18\x18 \x01(\t\x12\x0b\n\x03uid\x18\x64 \x01(\x03\x12\x11\n\ttimestamp\x18\x65 \x01(\x03\"\x19\n\x08Nested15\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MajorLogin_res_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAJORLOGINRES']._serialized_start=37
  _globals['_MAJORLOGINRES']._serialized_end=434
  _globals['_NESTED15']._serialized_start=436
  _globals['_NESTED15']._serialized_end=461
# @@protoc_insertion_point(module_scope)
